minify hook check for npx instead of global minify

diff --git a/.git-hooks/pre-commit b/.git-hooks/pre-commit
--- a/.git-hooks/pre-commit
+++ b/.git-hooks/pre-commit
@@ -1,9 +1,7 @@
 #!/bin/bash
 
-MINIFY_COMMAND="minify"
-
-if ! command -v $MINIFY_COMMAND &> /dev/null;then
-    echo "command $MINIFY_COMMAND could not be found"
+if ! command -v "npx" &> /dev/null;then
+    echo "ERROR: npx could not be found"
     exit 1
 fi
 
